In [6]:
!pip install tensorflow

  Using cached tensorflow-2.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached termcolor-3.2.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached wrapt-2.0.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (9.0 kB)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached h5py-3.15.1-cp312-cp312-manylinux_2_27_x86_64.manyl

In [7]:
# import tensorflow as tf
# print(tf.__version__)


In [8]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

2025-11-12 17:42:15.671589: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-12 17:42:16.198112: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-12 17:42:18.889704: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [10]:
with open("tinyshakespeare.txt", "r", encoding="utf-8") as f:
    text = f.read()

In [ ]:
lines = [ln.strip() for ln in text.splitlines() if ln.strip()]

In [56]:
tokenizer = Tokenizer(num_words=NUM_WORDS, oov_token="<OOV>")

In [70]:
tokenizer.fit_on_texts(lines)

In [58]:
tokenizer.word_index

{'<OOV>': 1,
 'gloucester:': 2,
 'duke vincentio:': 3,
 'romeo:': 4,
 'menenius:': 5,
 'petruchio:': 6,
 'coriolanus:': 7,
 'king richard iii:': 8,
 'isabella:': 9,
 'juliet:': 10,
 'leontes:': 11,
 'sicinius:': 12,
 'lucio:': 13,
 'king edward iv:': 14,
 'queen elizabeth:': 15,
 'warwick:': 16,
 'king richard ii:': 17,
 'brutus:': 18,
 'buckingham:': 19,
 'henry bolingbroke:': 20,
 'nurse:': 21,
 'tranio:': 22,
 'queen margaret:': 23,
 'angelo:': 24,
 'katharina:': 25,
 'escalus:': 26,
 'camillo:': 27,
 'duchess of york:': 28,
 'king henry vi:': 29,
 'hortensio:': 30,
 'baptista:': 31,
 'cominius:': 32,
 'autolycus:': 33,
 'clarence:': 34,
 'provost:': 35,
 'benvolio:': 36,
 'clown:': 37,
 'grumio:': 38,
 'prospero:': 39,
 'mercutio:': 40,
 'lucentio:': 41,
 'paulina:': 42,
 'york:': 43,
 'pompey:': 44,
 'gremio:': 45,
 'volumnia:': 46,
 'polixenes:': 47,
 'hastings:': 48,
 'friar laurence:': 49,
 'duke of york:': 50,
 'northumberland:': 51,
 'lady anne:': 52,
 'capulet:': 53,
 'aufid

In [71]:
vocab_size = len(tokenizer.word_index) + 1

In [72]:
input_sequences = []
for sentence in lines:
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    if len(tokenized_sentence) < 2:
        continue
    for i in range(1, len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

In [73]:
input_sequences

[[89, 284],
 [141, 36],
 [141, 36, 1],
 [141, 36, 1, 146],
 [141, 36, 1, 146, 733],
 [141, 36, 1, 146, 733, 128],
 [141, 36, 1, 146, 733, 128, 16],
 [141, 36, 1, 146, 733, 128, 16, 103],
 [103, 103],
 [89, 284],
 [7, 41],
 [7, 41, 34],
 [7, 41, 34, 1],
 [7, 41, 34, 1, 376],
 [7, 41, 34, 1, 376, 4],
 [7, 41, 34, 1, 376, 4, 206],
 [7, 41, 34, 1, 376, 4, 206, 64],
 [7, 41, 34, 1, 376, 4, 206, 64, 4],
 [7, 41, 34, 1, 376, 4, 206, 64, 4, 1],
 [1, 1],
 [89, 284],
 [89, 7],
 [89, 7, 92],
 [89, 7, 92, 1],
 [89, 7, 92, 1, 242],
 [89, 7, 92, 1, 242, 12],
 [89, 7, 92, 1, 242, 12, 1],
 [89, 7, 92, 1, 242, 12, 1, 637],
 [89, 7, 92, 1, 242, 12, 1, 637, 4],
 [89, 7, 92, 1, 242, 12, 1, 637, 4, 2],
 [89, 7, 92, 1, 242, 12, 1, 637, 4, 2, 327],
 [36, 1],
 [36, 1, 36],
 [36, 1, 36, 1],
 [89, 284],
 [71, 79],
 [71, 79, 555],
 [71, 79, 555, 27],
 [71, 79, 555, 27, 3],
 [71, 79, 555, 27, 3, 399],
 [71, 79, 555, 27, 3, 399, 24],
 [71, 79, 555, 27, 3, 399, 24, 1],
 [71, 79, 555, 27, 3, 399, 24, 1, 55],
 [71, 7

In [62]:
max_len = max([len(x) for x in input_sequences])
max_len

16

In [74]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [75]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  89, 284],
       [  0,   0,   0, ...,   0, 141,  36],
       [  0,   0,   0, ..., 141,  36,   1],
       ...,
       [  0,   0,   0, ...,   0,   1,  26],
       [  0,   0,   0, ...,   1,  26, 133],
       [  0,   0,   0, ...,  26, 133,   1]],
      shape=(171312, 16), dtype=int32)

In [76]:
X = padded_input_sequences[:, :-1].astype('int32')
X

array([[  0,   0,   0, ...,   0,   0,  89],
       [  0,   0,   0, ...,   0,   0, 141],
       [  0,   0,   0, ...,   0, 141,  36],
       ...,
       [  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1,  26],
       [  0,   0,   0, ...,   1,  26, 133]],
      shape=(171312, 15), dtype=int32)

In [77]:
y = padded_input_sequences[:, -1].astype('int32')
y

array([284,  36,   1, ...,  26, 133,   1], shape=(171312,), dtype=int32)

In [78]:
X.shape

(171312, 15)

In [79]:
y.shape

(171312,)

In [80]:
vocab_size = NUM_WORDS + 1
input_len = X.shape[1]

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=vocab_size)

ImportError: cannot import name 'sparse_categorical_crossentropy' from 'tensorflow.keras.utils' (/home/no0ne/Documents/machine-learning/ML-Projects/.venv/lib/python3.12/site-packages/keras/_tf_keras/keras/utils/__init__.py)

In [82]:
y.shape

(171312, 1001)

In [83]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(NUM_WORDS, 100, input_length=56))
model.add(LSTM(150))
model.add(Dense(NUM_WORDS, activation='softmax'))

model.build(input_shape=(None, 56))

/home/no0ne/Documents/machine-learning/ML-Projects/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-11-12 18:23:47.386349: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [85]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [86]:

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 283)            │        42,733 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [87]:
model.fit(X,y,epochs=100)

2025-11-12 18:23:54.275859: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 685933248 exceeds 10% of free system memory.


Epoch 1/100


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1001), output.shape=(None, 283)

In [ ]:
import numpy as np
import time
text = "what is the fee"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

In [ ]:
tokenizer.word_index